Endpoint_parser
openziti/ziti-ops pull request #5
Opened 2023-08-18 12:45 UTC by mikegorman-nf

Add router filters and shell in endpoint parser function.

2023-08-18 14:04 UTC, plorenz commented on .idea/.gitignore
Can we remove the .idea files and add .idea to .gitignore as well, please? Same for .vscode

2023-08-18 14:48 UTC, plorenz requested changes
Other than the IDE files being added, looks good.

2023-08-21 18:22 UTC, qrkourier commented on .idea/.gitignore
@mikegorman-nf You can do this to keep your local copy while removing them from Git.

```bash
git rm --cached ./.vscode ./.idea
```

2023-08-21 20:00 UTC, plorenz approved these changes
Looks good!

2023-08-21 20:13 UTC, merged